### ISSUE TITLE
Any way to remove default or change the name and add description

### ISSUE THREAD

**Issue by wighawag** [enzonotario/vitepress-openapi#109]
### What would you like?

Right now It generate such page 
![Screenshot from 2024-11-02 07-52-31](https://github.com/user-attachments/assets/60d34cb7-947e-40a1-9888-990a736513e3)

would like to remove Default on the side and move the table of content to the left

Or alternatively, if I could change the name and add a description so the left do not feel emptu

**Comment by enzonotario** [comment]
Hi @wighawag , there are a few options here:

1. Without updating your `openapi.json`: You can change the default tag name by setting the `defaultTag` config. I've also added an option to specify the `defaultTagDescription` in #114 , so now you can have something like [this](https://stackblitz.com/edit/enzonotario-vitepress-openapi-starter-enucfv?file=docs%2F.vitepress%2Ftheme%2Findex.ts)
2. Updating your `openapi.json`: You can specify the `tags` for each operation, and/or define the [TagObject](https://spec.openapis.org/oas/latest.html#tag-object) in your `openapi.json`
3. Hide the section and add a custom component: You could also configure it to hide that section, and maybe add your own component above it by using:
	```
	spec: {
	  defaultTag: 'Custom Default Tag',
	  defaultTagDescription: 'Custom Default Tag Description',
	  showPathsSummary: false, // <-- Add this
	  groupByTags: false, // <-- Also maybe this
	},
	```

If you go with option 1. or 2., maybe the design could be improved. Any suggestions are welcome!
