### ISSUE TITLE
api should appear in search

### ISSUE THREAD

**Issue by wighawag** [enzonotario/vitepress-openapi#115]
### What would you like?

Currently, When typing in the search box, no api get shown even if they should match the query

**Comment by enzonotario** [comment]
Hi @wighawag , it's duplicated of #47 , you can try [this](https://github.com/enzonotario/vitepress-openapi/issues/47#issuecomment-2356153847) to get it working. Also, for Algolia for example, it works fine, as you can see in https://vitepress-openapi.vercel.app/
