### ISSUE TITLE
Add tags slot

### ISSUE THREAD

**Issue by stereobooster** [enzonotario/vitepress-openapi#120]
### What would you like?

List of tags underneath the title

### Why is this needed?

Would be handy with tags pages, if one doesn't show tags in the sidebar (without `itemsByTags`)

### How could it be implemented?

I use following workaround

```vue
<OAOperation :operationId="operationId" :isDark="isDark" >
  <template #description="description">
    <div>
      <Badge type="info" v-for="tag in operation.tags">
        <!-- hardocde prefix, tell me if you know better way -->
        <a :href="`/tags/${tag}`">{{ tag }}</a>
      </Badge>
    </div>
  </template>
</OAOperation>
```

But would be nice to have

```ts
useTheme({
    operation: {
        slots: ['tags']
   }
})
```

### Other information

Related: it would be nice to have more compact representation of endpoints lists for tags pages. For now I use

```ts
import { useTheme } from 'vitepress-openapi'
useTheme({
    operation: {
        slots: [
            'header',
            'path',
            'description',
        ],
        cols: 2,
    },
})
```

Which looks a bit strange

**Comment by enzonotario** [comment]
Hi @stereobooster , 

Regarding the `tags` slot, I've added it in [v0.0.3-alpha.50](https://github.com/enzonotario/vitepress-openapi/releases/tag/v0.0.3-alpha.50). You can find the documentation for it here: https://vitepress-openapi.vercel.app/customizations/operation-tags-slot.html

As for the "more compact representation", if you're referring to the space between different operations slots, I've reduced it from `space-y-8` to `space-y-4`. However, you can always customize it by using your own styles, for example:

```css
/* Using CSS */
.OAPath > :not([hidden]) ~ :not([hidden]) {
  margin-top: 0;
}

/* Using TailwindCSS */
/*.OAPath {
  @apply space-y-0
}*/
```

Here's a [StackBlitz example](https://stackblitz.com/edit/enzonotario-vitepress-openapi-starter-dgzbza?file=docs%2F.vitepress%2Ftheme%2Fstyle.css)

If you have a better proposal for a compact layout, we could consider adding it as an alternative layout. Feel free to open a new issue with your suggestion.

Thanks for the suggestions, and any additional feedback is welcome!
