### ISSUE TITLE
Overwrite "Try It Out" url

### ISSUE THREAD

**Issue by lundjrl** [enzonotario/vitepress-openapi#127]
### What would you like?

The ability to change the default url/port for the "Try It Out" button. 

### Why is this needed?

The API I'm building has different ports for different things. In my specific case, the current behavior does not invoke my api. 

### How could it be implemented?

Could we possibly  have an additional env variable that overwrites the default behavior?

**Comment by enzonotario** [comment]
Hi @lundjrl , I'm working on it in #136 , can you please validate it via [pkg-pr-new release](https://github.com/enzonotario/vitepress-openapi/pull/136#issuecomment-2542517085) ? You can also check this [StackBlitz example](https://stackblitz.com/edit/enzonotario-vitepress-openapi-starter-9pzhnmd3?file=docs%2F.vitepress%2Ftheme%2Findex.ts)

I'm not sure about your specific use case, but if your Spec doesn't include any Servers, you can set a default one. You can also define Servers at the Operation level, or even set a custom function to get Server/s dynamically.

Any feedback is welcome, thanks!
