### ISSUE TITLE
Multilenguaje 

### ISSUE THREAD

**Issue by fcoagz** [enzonotario/vitepress-openapi#128]
Seria interesante que haya una documentación que logre adaptarse al lenguaje seleccionado desde un selector. Ya dependería de uno agregar algún lenguaje adicional en nuestra docs del proyecto.

**Comment by enzonotario** [comment]
Hola @fcoagz , en #137 agregué soporte para esto:

- Ahora es posible configurar el `locale` dinámicamente vía [`useTheme` composable](https://vitepress-openapi.vercel.app/customizations/i18n.html).
- También se agregó un [componente `OALocaleSelect`](https://vitepress-openapi.vercel.app/customizations/i18n.html#oalocaleselect-component) que permite seleccionar entre los `availableLocales`. Aunque esto sólo modificará el idioma de la UI relacionada a `vitepress-openapi`, y no a todo `vitepress`.
- Para una mejor integración, es recomendable implementar primero el [i18n en VitePress](https://vitepress.dev/guide/i18n), y luego utilizar [`useTheme` para configurar el lenguaje actual](https://vitepress-openapi.vercel.app/customizations/i18n.html#internationalization-i18n). Un [ejemplo](https://vitepress-openapi-i18n.vercel.app/) de esto se puede ver en [este Repositorio](https://github.com/enzonotario/vitepress-openapi-i18n) .

Cualquier feedback es bienvenido, gracias!

**Comment by fcoagz** [comment]
Gracias, amigo. Ya le hecho un vistazo
