### ISSUE TITLE
Support multiple security together when specified

### ISSUE THREAD

**Issue by Tiffceet** [enzonotario/vitepress-openapi#129]
### What would you like?

Currently, each endpoint can only use 1 securityScheme despite OAS 3 being able to specify multiple securityScheme must be used together 
https://swagger.io/docs/specification/v3_0/authentication/#using-multiple-authentication-types

Defining security schemes:
```json
"securitySchemes": {
      "ApiKeyAuth": {
        "type": "http",
        "scheme": "bearer",
        "description": "API Key"
      },
      "Signature": {
        "name": "x-signature",
        "type": "apiKey",
        "in": "header",
        "description": "Request signature"
      }
    },
```

In endpoint:
```json
"security": [{ "Signature": [] }, { "ApiKeyAuth": [] }],
```

### Why is this needed?

When allowing user to test the endpoints, if the API requires 2+ security schemes to be used together, the try it would not able to show 2 security fields
![image](https://github.com/user-attachments/assets/fff542ec-4b04-4635-b813-37031b0f451e)

### How could it be implemented?

Updating OASecurity and OATryWithVariables

### Other information

Example implementation from [Scalar](https://github.com/scalar/scalar):
![image](https://github.com/user-attachments/assets/930d693d-6a1e-4261-833a-495acb8f8d35)

**Comment by enzonotario** [comment]
Hi @Tiffceet , it's now supported in [v0.0.3-alpha.54](https://github.com/enzonotario/vitepress-openapi/releases/tag/v0.0.3-alpha.54). Can you please validate it? You can also see an [example here](https://vitepress-openapi.vercel.app/tests/security.html).

Thanks!
