### ISSUE TITLE
Display better response examples for arrays of a schema

### ISSUE THREAD

**Issue by addshore** [enzonotario/vitepress-openapi#131]
### What would you like?

To be able to define a schema such as the following as a content response

```
                "schema": {
                  "type": "array",
                  "items": {
                    "$ref": "#/components/schemas/datapoint"
                  }
                }
```

And have it display an example using the datapoint schema, rather than just displaying `[]`

### Why is this needed?

More useful infomation via examples to users.

### Other information

Current example just looks like this

![image](https://github.com/user-attachments/assets/82c3e90e-7823-4209-9aa5-d3f92d9d9f77)

**Comment by enzonotario** [comment]
Hi @addshore , can you please share the full OpenAPI specification? maybe it's not resolving reference correctly, because I see it's working fine for [current OpenAPI example](https://stackblitz.com/edit/enzonotario-vitepress-openapi-starter-qgnzbpc3?file=public%2Fopenapi.json), with:

```json
"responses": {
  "200": {
    "description": "OK",
    "content": {
      "application/json": {
        "schema": {
          "type": "array",
          "items": {
            "$ref": "#/components/schemas/Artist"
          }
        }
      }
    }
  }
}
```

**Comment by enzonotario** [comment]
Mm yes, it would be better to be specific and include a `type`, since it's required by the Specification.

However, the parser can also be a bit smarter and determine it based in the value. So I've added this in [v0.0.3-alpha.51](https://github.com/enzonotario/vitepress-openapi/releases/tag/v0.0.3-alpha.51).

Thanks!

**Comment by addshore** [comment]
Amazing, many thanks!
