### ISSUE TITLE
Is it possible to add vitepress-openapi to an existing Vitepress site as a menu item

### ISSUE THREAD

**Issue by glennsc** [enzonotario/vitepress-openapi#71]
### What would you like?

Vitepress-openapi is beautiful.  I have a doc site already, and I would like to add the vitepress-openapi docs as a menu item on my top navigation menu. 

![CleanShot 2024-10-06 at 17 49 51@2x](https://github.com/user-attachments/assets/940bfcb0-cdee-4d71-8ca4-4e52cf50cfc9)

### Why is this needed?

There is often a lot of material besides the openapi specification that one needs for documentation.  I'd like to be able to include the openapi site within another site to keep everything together.

### How could it be implemented?

I'm not knowledgeable enough to know.  Right now I am embedding `openapi-explorer` in a simple `layout: page` page associated with the menu item:

```vue
---
layout: page
sidebar: false
---
<script setup>
  import 'openapi-explorer/dist/es/openapi-explorer.js';
  import { useData } from 'vitepress'
  const { isDark, theme, page, frontmatter } = useData()
</script>

<Clientonly>
  <openapi-explorer
    v-if = isDark
    spec-url = "/adm-spec.yaml"
    hide-console = true
    hide-authentication = true
    hide-server-selection = true
    hide-components = false
    nav-bg-color = #1b1b1f
    secondary-color = #F8F8F5
    nav-hover-text-color = #85bd4f
    bg-color = #1b1b1f
    text-color = "#F8F8F5"
  >
  </openapi-explorer>


  <openapi-explorer
    v-else
    spec-url = "/adm-spec.yaml"
    hide-console = true
    hide-authentication = true
    hide-server-selection = true
    hide-components = false
    nav-bg-color = #ffffff
    secondary-color = #000000
    nav-hover-text-color = #F8F8F5
  >
  </openapi-explorer>

</ClientOnly>
```

This seems very awkward, and it's difficult to get the styles to match Vitepress's theme.  Might there be a way to extend the default theme with a layout called `openapi` and somehow link my spec file in the front matter?

### Other information

I appreciate this work very much.  Thanks for considering the suggestion.

**Comment by enzonotario** [comment]
Hi @glennsc , do you mean to have something like this? https://vitepress-openapi-starter.vercel.app/reference.html ([Repository](https://github.com/enzonotario/vitepress-openapi-starter))
    
In that case, you are looking for [All Operations Layout](https://vitepress-openapi.vercel.app/layouts/all-operations.html), and specifying OpenAPI Specification as shown in the [Multiple Specs Example](https://vitepress-openapi.vercel.app/layouts/multiple-specs.html). You can also configure the FrontMatter as shown in the Starter Repository.

I know maybe it's not well documented. PRs are welcome!

**Comment by enzonotario** [comment]
Hi @glennsc, does it answer your question? If so, I'd like to close this issue.

It not, please clarify a bit more what is needed. I know there are many missing features, like the recently added "Group by Tags" in #82, but I need to address them progressively.

Thank you so much for your words, feel free to suggest any other features!

**Comment by glennsc** [comment]
Okay @enzonotario [all operations layout](https://vitepress-openapi.vercel.app/layouts/all-operations.html)  seems to work very nicely.  My API will have lots of operations so navigating a long page may be difficult -- Is there some way to get the operations to autogenerate the sidebar items as described [here](https://vitepress-openapi.vercel.app/layouts/sidebar.html)?

**Comment by enzonotario** [comment]
Hi @glennsc ,

When using `OASpec` component ([All operations layout](https://vitepress-openapi.vercel.app/layouts/all-operations.html)), it can't generate the left sidebar, but it can generate the "right sidebar" (`aside` section), as you can see in: https://vitepress-openapi.vercel.app/example/one-page.html

For this, you have to use VitePress FrontMatter:

```
---
aside: true
outline: [1, 2]
title: vitepress-openapi
---
```


You can also group by tags, collapse paths, etc. (https://vitepress-openapi.vercel.app/composables/useTheme.html)

So far, the "left sidebar" only works for [One operation layout](https://vitepress-openapi.vercel.app/layouts/one-operation.html).

**Comment by glennsc** [comment]
Thank you!  That works!
