### ISSUE TITLE
Group operations into tags groups

### ISSUE THREAD

**Issue by ashercoren** [enzonotario/vitepress-openapi#81]
### What would you like?

When operations with different tags are rendered on the same page, they should be grouped by tags, as it happens in Swagger.
![image](https://github.com/user-attachments/assets/1c11a735-cf63-4bfa-918c-2f2137f72d19)

**Comment by enzonotario** [comment]
Hi @ashercoren , this would be a great addition, thanks for suggesting it!

However, I think there are some design decisions to be made. I'm working on it in #82, and you can try it out by installing the [pkg-pr-new](https://github.com/enzonotario/vitepress-openapi/pull/82#issuecomment-2406431758) package. I'd appreciate any feedback. You can also see a preview online at: https://vitepress-openapi-git-feature-spe-547c15-enzo-notarios-projects.vercel.app/example/one-page.html

**Comment by addshore** [comment]
Currently I do this by hand making use of the generateSitebarGroup methods

```
            {
              text: 'Version 2',
              link: '/apis/v2/',
              collapsed: false,
              items: [
                collapse(sidebarSpec2.generateSidebarGroup({
                  tag: ["auth"],
                  text: "Authentication",
                  linkPrefix: '/apis/v2/',
                  addedOperations: new Set(),
                })),
                collapse(sidebarSpec2.generateSidebarGroup({
                  tag: ["users", "published"],
                  text: "Users",
                  linkPrefix: '/apis/v2/',
                  addedOperations: new Set(),
                })),
              ],
            },
```

**Comment by enzonotario** [comment]
@addshore yes, but that is for the Sidebar, right?

I think here we're talking about grouping Pahts by Tags in the "content section". Or am I misunderstanding something?

Regarding your Sidebar Example, it's perfect! Just note that you can omit the `addedOperations: new Set()` param, as it already defaults to `new Set()` for `addedOperations` when no present.
