### ISSUE TITLE
menu item text not rendering at build (after `^0.0.3-alpha.31` to `0.0.3-alpha.37`)

### ISSUE THREAD

**Issue by addshore** [enzonotario/vitepress-openapi#84]
Running `docs:dev` results in correct menu items

![image](https://github.com/user-attachments/assets/742349aa-2cf7-4ead-aca6-6bc41aa8be46)

However when actually built, the menu item text doesnt get added

![image](https://github.com/user-attachments/assets/b3a0ab87-72c0-4820-b7db-948924c806d5)

I experienced this while moving from `^0.0.3-alpha.31` to `0.0.3-alpha.37`

**Comment by addshore** [comment]
Coming back around to this, I don't think this has anything to do with the library version, I believe I have broken it another way somehow.
I'll continue to investigate.

**Comment by enzonotario** [comment]
mm I think it is related to this library. I experimented that after some page refresh. I thought it was just me. I will check it. Maybe the nested `p` tag is causing some SSR issues.

**Comment by enzonotario** [comment]
@addshore it's fixed now in [v0.0.3-alpha.38](https://github.com/enzonotario/vitepress-openapi/releases/tag/v0.0.3-alpha.38).

Can you please validate it?

**Comment by addshore** [comment]
yup! its all back!

![image](https://github.com/user-attachments/assets/d0ad0387-e9e8-4a51-acb7-a3f6beb1a302)

Many thanks!
