### ISSUE TITLE
Display example values for Parameters

### ISSUE THREAD

**Issue by atlemagnussen** [enzonotario/vitepress-openapi#93]
### What would you like?

Parameter example values along with the description

So for example after I overloaded your template for this section I see this:

**$filter** string
Example name eq 'hello'

You can see the example [live here](https://apidev.digilean.tools/docs/operations/Boards_List) as well

### Why is this needed?

I see you use the example values in the playground/try it section

But I choose not to display this.

### How could it be implemented?

Something like 
```vue
<div v-if="props.parameter.example" class="flex flex-row space-x-2">
    <span class="text-sm example font-bold">
        Example
    </span>
    <span class="text-sm text-gray-600 dark:text-gray-300">
        {{ props.parameter.example }}
    </span>
</div>
```

**Comment by enzonotario** [comment]
Hi @atlemagnussen , I added this in [v0.0.3-alpha.43](https://github.com/enzonotario/vitepress-openapi/releases/tag/v0.0.3-alpha.43). 

Can you please validate it? thanks for reporting!

**Comment by atlemagnussen** [comment]
> Hi @atlemagnussen , I added this in [v0.0.3-alpha.43](https://github.com/enzonotario/vitepress-openapi/releases/tag/v0.0.3-alpha.43).
> 
> Can you please validate it? thanks for reporting!

Looks very good. Thank you! Great extension overall btw  :)
